### PR TITLE
Add WWOO and Hot Furnace + other things

### PR DESCRIPTION
**Pull request by Zekiu**
*Added "William Wythers' Overhauled Overworld" to Worldgen

*Added "Hot Furnace" back (seems like the project is no longer abandoned)

*Added Modrinth pages to some of the mods

*Changed "persistend entities" mod page to link to Modrinth, as the project has moved there (According to it's CurseForge page)

*Changed "Krypton" mod page to link to Modrinth and CurseForge (more user-friendly imo)

### CODE REVIEW

**Comment by Patbox** [comment]
William Wythers' Overhauled Overworld isn't really a mod, it's a datapack

**Comment by Zekiu** [comment]
It's available as a mod on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld)

**Comment by Patbox** [comment]
Yeah, but it's still just a datapack packed as mod (and will cause incompatibilities with other worldgen mods)

**Comment by comp500** [comment]
For now I don't want to add additional Modrinth/CurseForge links to the mods; I'm planning to develop a more organised structure for the mod metadata along with some scripts to build lists (including modrinth/curseforge/github links and descriptions) to make it easier to maintain.

**Comment by Zekiu** [comment]
I'll close the PR for now and wait for the overhaul of the repo.

**Pull request closed without merging**
